### ISSUE TITLE
print문 등이 맨 위에 끼어 있는 경우는 인정하나요?

### ISSUE THREAD

**Issue by Re-st** [Re-st/DDAFL-experiment#6]
우리 도커의 log
```shell
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2566==ERROR: AddressSanitizer: stack-overflow on address 0x7ffccc1d5dc8 (pc 0x00000048e911 bp 0x7ffccc1d6650 sp 0x7ffccc1d5dd0 T0)
    #0 0x48e911 in printf_common(void*, char const*, __va_list_tag*) /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_format.inc:496:3
    #1 0x48f3e9 in vsnprintf /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1651:1
    #2 0x695046 in Exiv2::Internal::stringFormat[abi:cxx11](char const*, ...) /benchmark/RUNDIR-exiv2-0.26-trunk/exiv2-trunk/src/image.cpp:975:20
    #3 0x68bab5 in Exiv2::Image::printIFDStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, unsigned int, bool, char, int) /benchmark/RUNDIR-exiv2-0.26-trunk/exiv2-trunk/src/image.cpp:357:51
    #4 0x68f787 in Exiv2::Image::printIFDStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, unsigned int, bool, char, int) /benchmark/RUNDIR-exiv2-0.26-trunk/exiv2-trunk/src/image.cpp:445:29

``` 

CVE 설명 Link의 log
```shell
ASAN:DEADLYSIGNAL
=================================================================
==621==ERROR: AddressSanitizer: stack-overflow on address 0x7ffcbaecbff8 (pc 0x0000004d6c3f bp 0x0ff43348f15c sp 0x7ffcbaecc000 T0)
    #0 0x4d6c3e in __sanitizer::mem_is_zero(char const*, unsigned long) (/exiv2/build/bin/exiv2+0x4d6c3e)
    #1 0x4c0f11 in __asan_region_is_poisoned (/exiv2/build/bin/exiv2+0x4c0f11)
    #2 0x466332 in printf_common(void*, char const*, __va_list_tag*) (/exiv2/build/bin/exiv2+0x466332)
    #3 0x468dbd in __interceptor_vsnprintf (/exiv2/build/bin/exiv2+0x468dbd)
    #4 0x7fa19a17fcde in Exiv2::Internal::stringFormat[abi:cxx11](char const*, ...) /exiv2/src/image_int.cpp:48:23
    #5 0x7fa199f05fe5 in Exiv2::Image::printIFDStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, unsigned int, bool, char, int) /exiv2/src/image.cpp:415:24
    #6 0x7fa199f08468 in Exiv2::Image::printIFDStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, unsigned int, bool, char, int) /exiv2/src/image.cpp:446:29
    #7 0x7fa199f08468 in Exiv2::Image::printIFDStructure(Exiv2::BasicIo&, std::ostream&, Exiv2::PrintStructureOption, unsigned int, bool, char, int) /exiv2/src/image.cpp:446:29

``` 
즉, stack-overflow임은 같고, Exiv2 함수 log까지 같은데, (stringFormat 함수가 있는 파일 위치는 다릅니다.. 아마 버전이 올라가며 옮긴 듯하네요) 그 뒤에 vsnprintf 등이 붙습니다. 이것들은 버전이 올라가며 디버깅 용도로 만든 거 아닐까요? 인정하고 이 인풋으로 결정해도 될까요?

**Comment by Re-st** [comment]
인정하기로 결론
